apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-house
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coffee-house
  template:
    metadata:
      labels:
        app: coffee-house
    spec:
      containers:
        - name: coffee-house
          image: linusindevops/coffee-house:23
          ports:
            - containerPort: 5000
