apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: coffee-house
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: coffee-house-service  # The service for active traffic
      previewService: coffee-house-preview-service  # The preview service for testing new releases
      autoPromotionEnabled: false  # Manually promote new versions
  selector:
    matchLabels:
      app: coffee-house
  template:
    metadata:
      labels:
        app: coffee-house
    spec:
      containers:
        - name: coffee-house
          image: linusindevops/coffee-house:76  # Jenkins will update this
          ports:
            - containerPort: 5000
