apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: coffee-house
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: coffee-house
  template:
    metadata:
      labels:
        app: coffee-house
    spec:
      containers:
        - name: coffee-house
          image: linusindevops/coffee-house:81
          ports:
            - containerPort: 5000
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 50
        - pause: {duration: 60s}
        - setWeight: 100