apiVersion: v1
kind: Service
metadata:
  name: coffee-house-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: coffee-house
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
